# https://hackernoon.com/nats-jetstream-a-new-way-to-create-resilient-message-queue
# This version works great, maps the local /data directory to the NATS server's /data directory, and sets up a 3-node cluster with JetStream enabled.
# The NATS server is exposed on port 4222, the HTTP management port is exposed on port 8222, and the cluster (routes) port is exposed on port 6222.
# The NATS server is configured with the --jetstream flag, the --cluster_name flag is set to nats-jetstream-cluster, the --server_name flag is set to nats-1, the --cluster flag is set to nats://
# The routes are also setup correctly.
version: "3.5"
services:
  nats1:
    container_name: nats1
    image: nats
    entrypoint: /nats-server
    command: --server_name N1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats2:4245,nats://nats3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4222:4222

  nats2:
    container_name: nats2
    image: nats
    entrypoint: /nats-server
    command: --server_name N2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4223:4222

  nats3:
    container_name: nats3
    image: nats
    entrypoint: /nats-server
    command: --server_name N3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245 -p 4222
    networks:
      - nats
    ports:
      - 4224:4222

networks:
  nats:
    name: nats